# Generated by Django 4.0.4 on 2022-06-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='genero',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
