# Generated by Django 4.0.4 on 2022-07-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsgPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('contenido', models.TextField(max_length=3000)),
                ('autor', models.CharField(max_length=40)),
                ('post', models.IntegerField()),
            ],
        ),
    ]
